export const PROVIDER_DB_NAME = "fixbee_business_directory_provider.db";

export const DEFAULT_PROVIDER_CATEGORY = "plumber";
export const DEFAULT_PROVIDER_CITY = "Vancouver";
export const DEFAULT_PROVIDER_LIMIT = 20;
export const MAX_SELECTED_PROVIDERS = 5;

export const SUPPORTED_CITIES = [
  "Vancouver",
  "Burnaby",
  "Richmond",
  "Surrey",
  "North Vancouver",
  "West Vancouver",
  "New Westminster",
  "Delta",
];
export const DEMO_PROVIDERS = [
  {
    id: "demo-apex-repair-solutions",
    mongoId: "demo-apex-repair-solutions",
    businessName: "Apex Repair Solutions",
    businessDescription:
      "Licensed plumbing experts specializing in emergency leak repairs and residential maintenance.",
    providerType: "Plumbing",
    primaryCategory: "Plumbing",
    phoneDisplay: "+1 604-555-0182",
    phoneNormalized: "+16045550182",
    email: "apex.demo@example.com",
    address: "626 Kingsway, Vancouver, BC",
    city: "Vancouver",
    province: "BC",
    rating: 4.9,
    reviewCount: 128,
    websiteUrl: "https://example.com/apex-repair-solutions",
    latitude: 49.257107,
    longitude: -123.0911868,
    sourceNames: ["google"],
  },
  {
    id: "demo-primefix-experts",
    mongoId: "demo-primefix-experts",
    businessName: "PrimeFix Experts",
    businessDescription:
      "Fast plumbing and drainage support for urgent residential repair requests.",
    providerType: "Plumbing",
    primaryCategory: "Plumbing",
    phoneDisplay: "+1 778-555-0136",
    phoneNormalized: "+17785550136",
    email: "primefix.demo@example.com",
    address: "261 E 64th Ave, Vancouver, BC",
    city: "Vancouver",
    province: "BC",
    rating: 4.7,
    reviewCount: 156,
    websiteUrl: "https://example.com/primefix-experts",
    latitude: 49.2128581,
    longitude: -123.1008368,
    sourceNames: ["google", "yelp"],
  },
  {
    id: "demo-reliable-home-services",
    mongoId: "demo-reliable-home-services",
    businessName: "Reliable Home Services",
    businessDescription:
      "General repair professionals for leaks, fixtures, and home maintenance checks.",
    providerType: "Plumbing",
    primaryCategory: "Plumbing",
    phoneDisplay: "+1 604-555-0148",
    phoneNormalized: "+16045550148",
    email: "reliable.demo@example.com",
    address: "4820 Kingsway, Burnaby, BC",
    city: "Burnaby",
    province: "BC",
    rating: 4.8,
    reviewCount: 189,
    websiteUrl: "https://example.com/reliable-home-services",
    latitude: 49.226,
    longitude: -122.999,
    sourceNames: ["google"],
  },
  {
    id: "demo-metro-repair-pros",
    mongoId: "demo-metro-repair-pros",
    businessName: "Metro Repair Pros",
    businessDescription:
      "Metro Vancouver repair technicians available for plumbing and water damage calls.",
    providerType: "Plumbing",
    primaryCategory: "Plumbing",
    phoneDisplay: "+1 604-555-0164",
    phoneNormalized: "+16045550164",
    email: "metro.demo@example.com",
    address: "7900 Westminster Hwy, Richmond, BC",
    city: "Richmond",
    province: "BC",
    rating: 4.9,
    reviewCount: 132,
    websiteUrl: "https://example.com/metro-repair-pros",
    latitude: 49.17,
    longitude: -123.136,
    sourceNames: ["foursquare"],
  },
  {
    id: "demo-trusted-trade-services",
    mongoId: "demo-trusted-trade-services",
    businessName: "Trusted Trade Services",
    businessDescription:
      "Home repair service focused on clear estimates, reliable arrival windows, and simple communication.",
    providerType: "Plumbing",
    primaryCategory: "Plumbing",
    phoneDisplay: "+1 236-555-0119",
    phoneNormalized: "+12365550119",
    email: "trusted.demo@example.com",
    address: "1450 Lonsdale Ave, North Vancouver, BC",
    city: "North Vancouver",
    province: "BC",
    rating: 4.6,
    reviewCount: 94,
    websiteUrl: "https://example.com/trusted-trade-services",
    latitude: 49.32,
    longitude: -123.073,
    sourceNames: ["google"],
  },
  {
    id: "demo-fixwise-professionals",
    mongoId: "demo-fixwise-professionals",
    businessName: "FixWise Professionals",
    businessDescription:
      "Experienced providers for small plumbing issues, sink leaks, and water fixture repair.",
    providerType: "Plumbing",
    primaryCategory: "Plumbing",
    phoneDisplay: "+1 604-555-0177",
    phoneNormalized: "+16045550177",
    email: "fixwise.demo@example.com",
    address: "102 Columbia St, New Westminster, BC",
    city: "New Westminster",
    province: "BC",
    rating: 4.8,
    reviewCount: 87,
    websiteUrl: "https://example.com/fixwise-professionals",
    latitude: 49.205,
    longitude: -122.91,
    sourceNames: ["yelp"],
  },
  {
    id: "demo-swift-service-experts",
    mongoId: "demo-swift-service-experts",
    businessName: "Swift Service Experts",
    businessDescription:
      "Quick response repair team for nearby plumbing and household maintenance requests.",
    providerType: "Plumbing",
    primaryCategory: "Plumbing",
    phoneDisplay: "+1 778-555-0188",
    phoneNormalized: "+17785550188",
    email: "swift.demo@example.com",
    address: "104 Ave, Surrey, BC",
    city: "Surrey",
    province: "BC",
    rating: 4.9,
    reviewCount: 113,
    websiteUrl: "https://example.com/swift-service-experts",
    latitude: 49.19,
    longitude: -122.849,
    sourceNames: ["google"],
  },
  {
    id: "demo-bluepeak-maintenance",
    mongoId: "demo-bluepeak-maintenance",
    businessName: "BluePeak Maintenance",
    businessDescription:
      "Maintenance provider for plumbing checks, inspection follow-up, and repair planning.",
    providerType: "Plumbing",
    primaryCategory: "Plumbing",
    phoneDisplay: "+1 604-555-0199",
    phoneNormalized: "+16045550199",
    email: "bluepeak.demo@example.com",
    address: "Marine Dr, West Vancouver, BC",
    city: "West Vancouver",
    province: "BC",
    rating: 4.4,
    reviewCount: 120,
    websiteUrl: "https://example.com/bluepeak-maintenance",
    latitude: 49.328,
    longitude: -123.16,
    sourceNames: ["apify"],
  },
];
